# Generated by Django 4.2.2 on 2023-07-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRojas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='año',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='series',
            name='año',
            field=models.IntegerField(),
        ),
    ]
